server:
  port: 3344

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/Desktop/conf #git本地仓库uri
          #uri: https://github.com/userwuqing/myproject.git #git远程仓库uri
          #search-paths: {application}/{profile} #搜索路径
          #basedir: d:/data #git的本地目录
          #skip-ssl-validation: true #跳过ssl检测
          #timeout: 5 #设置连接github的超时时间
