server:
  port: 3344

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/Desktop/conf #git本地仓库uri测试通过,windows系统为///，其他为//
          #uri: https://github.com/userwuqing/myproject.git #git远程仓库uri，
          search-paths: config-center/eureka-server-conf,config-center/eureka-server-register-conf #搜索路径,搜索子目录必须配例如eureka-server-register-conf/xxx
          #basedir: d:/data #git的本地目录
          #skip-ssl-validation: true #跳过ssl检测
          #timeout: 5 #设置连接github的超时时间
