server:
  port: 9000

spring:
  application:
    name: localhost


eureka:
  client:
    fetch-registry: false #该模块作为服务注册中心不必注册自己
    register-with-eureka: false #该模块作为服务注册中心不必注册自己
    service-url:
      defaultZone: http://${spring.application.name}:${server.port}/eureka/ #这里集群时需要配置其他注册中心地址，不写自己的
  #server:
    # enable-self-preservation: true #启用eureka自我保护机制，默认开启（true），不建议关闭
