server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment8004
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #操作源数据类型
    driver-class-name: com.mysql.jdbc.Driver #驱动包
    url: jdbc:mysql://localhost:3306/wq #数据库url
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wq.entries

#服务别名，注册到zookeeper中心的服务
  cloud:
    zookeeper:
      #zookeeper服务器的地址于端口
      connect-string: zookeeper.com:2181