server:
  port: 9001

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server-register8000:8000/eureka/ #,http://eureka-server-register8001:8001/eureka/,http://eureka-server-register8002:8002/eureka/ #服务注册中心，集群时用逗号隔开

  instance:
    prefer-ip-address: true #采用ip注册
    instance-id: ${spring.application.name}:${server.port} #实例名
    non-secure-port: ${server.port}

info: #配置从eureka 点击的某个服务的详细信息
  app.name: ${spring.application.name}
  company.name: www.wuqing.com
  build.artifactid: $project.artifaceid$
  build.version: $project.version$