
server:
  port: 8001

spring:
  application:
    name: eureka-server-register8001 #若注册中心在单机集群，需要配置电脑hots的本地dns解析
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

profiles:
  active: eureka-server-register8001

eureka:
  client:
    fetch-registry: false #该模块作为服务注册中心不必注册自己
    register-with-eureka: false #该模块作为服务注册中心不必注册自己
    service-url:
      defaultZone: http://eureka-server-register8000:8000/eureka/,http://eureka-server-register8002:8002/eureka/
      #这里集群时需要配置其他注册中心地址，不写自己的
  #server:
    # enable-self-preservation: true #启用eureka自我保护机制，默认开启（true），不建议关闭

