server:
  port: 8001

spring:
  application:
    name: cloud-pyment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource #操作源数据类型
    driver-class-name: com.mysql.jdbc.Driver #驱动包
    url: jdbc:mysql://localhost:3306/wq #数据库url
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wq.entries
