server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #注册中心使用的是这个

  client:
    register-with-eureka: false #自己不注册自己，默认true
    #表示从eureka服务抓取已有的注册信息，默认true，单机可不管，集群必须为true
    fetch-registry: true
    service-url: #这里是map结构，defaultZone是key
      defaultZone: http://eureka7002.com:7002/eureka/

  server:
    enable-self-preservation: false #关闭自我保护机制,保证不可用的服务及时剔除，生产建议开
    eviction-interval-timer-in-ms: 2000 #单位ms


