server:
  port: 7000

spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:9000/test/test.do
          predicates:
            - Path=/

management:
  endpoints:
    web:
      exposure:
        include: "*" #启用查看路由表

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
